print("###############################################")
print("#                                             #")
print("#   Not Another Dumb (Text) Adventure v0.0.1  #")
print("#                                             #")
print("###############################################")
print(" ")